### ISSUE TITLE
FrontEnd: Add search bar

### ISSUE THREAD

**Issue by drex44** [drex44/good-food-guide#1]
We are designing the website frontend first so it will need a search bar.

This is react/ nextjs webapp. 
Use material UI component to add a new search bar at the top!

Read the readme.md for more information.

**Comment by mandardeshpande** [comment]
@drex44 : I would like to work on this... can I?

**Comment by drex44** [comment]
@rsmelo92, are you working on this?
if he's not then @mandardeshpande you can start working on this one. Just make sure we don't have duplicate PR.

**Comment by drex44** [comment]
PR #17 resolved this issue!
