### ISSUE TITLE
Update Readme on how to start Dev server

### ISSUE THREAD

**Issue by plug-n-play** [drex44/good-food-guide#13]
Update Readme on how to start Dev server

**Comment by maafaishal** [comment]
I have added Quick Start to start the project in Readme.md. Please check my PR#12

**Comment by drex44** [comment]
It is already available in Contributing.md!

**Comment by drex44** [comment]
@plug-n-play yes, It would be better if it's also in README.md
@maafaishal your PR has been merged! Thank you.

Closing the issue!
