### ISSUE TITLE
Create Disclaimer/Statutory Warning to consult doctor before eating!

### ISSUE THREAD

**Issue by plug-n-play** [drex44/good-food-guide#18]
It would be good to have a Disclaimer which says one must consult doctor before following the advices being given on the site especially because of Legal reasons.

**Comment by drex44** [comment]
@plug-n-play yes, nice idea.
I was thinking about creating a Terms and Conditions, Privacy policy and disclaimer policy.
Will add a link to each in the footer.
What are your thoughts?

**Comment by drex44** [comment]
@plug-n-play I have added terms page and gave a link to it in the footer!
