### ISSUE TITLE
FrontEnd: Implement a share button

### ISSUE THREAD

**Issue by drex44** [drex44/good-food-guide#22]
In the foodCard.js, there's a share button. right now it does not work.

Clicking on it should open a modal and it should have various buttons for FB, twitter, copy to clipboard etc buttons. 
content to share is the link to the foodDetails.js for a particular disease. 

This is a react/nextjs web app. comment for more information.

**Comment by AudreyLin** [comment]
Hi.  I'd like to work on this issue for a pull request for Hacktoberfest, please.  I'm a newbie to code, but have worked with React before.  Thanks.

**Comment by drex44** [comment]
yeah sure. comment if you need any help.

To implement the modal use material ui as we are using it throughout the website.
How to implement modal,
https://material-ui.com/utils/modal/

**Comment by AudreyLin** [comment]
Awesome.  Thank you.  Will do. Are there specific comirs/themes or logos that you would like to use that aren't listed in the repo?

**Comment by drex44** [comment]
No, we don't have a logo. we are waiting for a designer to contribute a logo! Just sharing the link is enough as of now. 
we will improve it later when we have enough content.

**Comment by AudreyLin** [comment]
Ok, cool.  I am not great at graphic design, but I know a few aspiring designers that I can ask.  I'll send them the pr to see if they can do it.  If not, I know a few tools that might help with that, too, but you can leave that open in case someone wants to work on it before I get to it.  Do you have a color theme or a specific idea that you want to spin into your design?  I can add them to the modal.  

  Also, are there already links to follow the site in social media?  They can also have an option to follow this site in the contact us section and to mention the link for more marketing purposes in the share feature...

**Comment by drex44** [comment]
Currently, I don't have any such social media account links but once the site is useful enough and have enough content, will create them. as of now, just create the modal with a link to its foodDetails page. the link to be shared is the same as learn more.

**Comment by AudreyLin** [comment]
OK.  No prob.  Thanks.

**Comment by drex44** [comment]
closed by #57
