### ISSUE TITLE
Find a way to better save food data!

### ISSUE THREAD

**Issue by drex44** [drex44/good-food-guide#3]
This is react/ nextjs webapp.

We will show foods to eat when you have a certain disease. currently, only one example disease is shown but we will add more data later.
we want the site to be static. So, suggest an idea or thought to save these. we can have json.

Read the readme.md for more information or comment if you need more information or help!

**Comment by maafaishal** [comment]
I have created a JSON component & integrate it with foodCard.js. Please check my PR#12

**Comment by drex44** [comment]
@maafaishal Thanks for the PR. It's merged!
