### ISSUE TITLE
FrontEnd: Add a back button

### ISSUE THREAD

**Issue by drex44** [drex44/good-food-guide#35]
The site is in react/ nextjs. The master branch is always live. check out the url from home code screen.

If you click on learn more, it navigates to foodDetails.js.
There should be a button (back arrow or something elegant) to go back to the main home page.

happy hacking! :)
comment below if you need help or want to work on this!

**Comment by LazzyGuy** [comment]
need someone @drex44 ?

**Comment by KBoohene** [comment]
I would like to work on this

**Comment by drex44** [comment]
@LazzyGuy, @KBoohene yes we need somebody to work on this. it's an open issue.
As you commented earlier, if you want to finish this @LazzyGuy then do it.
if you don't want to then @KBoohene can work on it.

In the meantime, you can work on other open issue @KBoohene.

**Comment by kartikpandey2** [comment]
@drex44  I am guessing why there is a need of back button .? user can get to the home screen using browser back button 🤔

**Comment by drex44** [comment]
It's for better UX. some people prefer using the back button as they trust can on it. it will lead to expected part of the website. so users trust it while a browser back button is ambiguous. if the website becomes complex then users tend to trust back button more than browser back button.
here are some similar thoughts on the back button,
https://ux.stackexchange.com/questions/36809/do-i-really-need-a-back-button
https://ux.stackexchange.com/questions/7909/do-users-understand-the-browser-back-button
