### ISSUE TITLE
FrontEnd: Create a new simple page

### ISSUE THREAD

**Issue by drex44** [drex44/good-food-guide#4]
This is react/ nextjs webapp.

If you go to the home page then it shows a learn more button. clicking on it should show a page with more details.

so create a simple component called detailedFoodDetails.js that shows the title of the disease passed. you can follow the instruction given [here](https://nextjs.org/learn/basics/create-dynamic-pages/adding-a-list-of-posts)

Read the readme.md for more information or comment if you need more information or help!

**Comment by codegagan** [comment]
looking into

**Comment by drex44** [comment]
@codegagan comment if you need any help! :)
