### ISSUE TITLE
FrontEnd: Search food feature: Pulls up specific foods that list their known benefits

### ISSUE THREAD

**Issue by drex44** [drex44/good-food-guide#49]
The site is in react/ NextJs. The master branch is always live. check out the URL from the home code screen.

Create a new page (see about.js to know how to create a new page.)(will discuss what to be named later).
In this page, display the list of disease which can be treated with the given food.
I will update on how the users will reach this page with the food query but right now take static value.

happy hacking! :)
comment below if you need help or want to work on this!

**Comment by KBoohene** [comment]
Would like to work on this

**Comment by drex44** [comment]
@KBoohene go ahead!

**Comment by drex44** [comment]
resolved by PR #55
