### ISSUE TITLE
FrontEnd: more informative detailedFoodDetails.js

### ISSUE THREAD

**Issue by drex44** [drex44/good-food-guide#5]
This is react/ nextjs webapp.
First, the issues #4 and #3 should be completed to do this.

change file detailedFoodDetails.js and show all the information about the foods to eat from the data source. you only need to show the information. 
no need to make it look better (we have another issue for that here #6 ).

Read the readme.md for more information or comment if you need more information or help!

**Comment by mread1208** [comment]
Looking into this one

**Comment by drex44** [comment]
@mread1208 okay thanks!
