### ISSUE TITLE
Get the browser langauge

### ISSUE THREAD

**Issue by drex44** [drex44/good-food-guide#51]
The site is in react/ NextJs. The master branch is always live. check out the URL from the home code screen.

ToDo,
1. Create a new component to get the language from the browser
2. store it in the local storage of the browser.
3. create a drop-down list with two values. first value should be "English" and other is the language fetched from the browser. the location of this drop-down should be right-hand side of the about button in navigation on.

happy hacking! :)
comment below if you need help or want to work on this!

**Comment by TomLandis** [comment]
I want to work on this!

**Comment by drex44** [comment]
@TomLandis yeah go on!
