### ISSUE TITLE
FrontEnd: Add information in Footer!

### ISSUE THREAD

**Issue by drex44** [drex44/good-food-guide#59]
The site is in react/ NextJs. The master branch is always live. check out the URL in the Readme.

Objective: This site is created by many developers and we want to appreciate it. you can submit PR for each task described below!
ToDo,
1. Add a new line saying "Crafted(less than and greater than sign often seen for code) with love(red heart symbol) by amazing people!"
2. amazing people in the above line is a link to another page. so use the about.js page as the reference and create a new page contributors.js in pages directory.
3. create a react component called contributors.js in components folder that fetches all information about contributors of this repo using GitHub API. Import this component in pages/contributors.js
4. Make the contributors.js component more intuitive.

happy hacking! :)
comment below if you need help or want to work on this!

**Comment by aestevens** [comment]
I'd be happy to look into this. 😃

**Comment by drex44** [comment]
@aestevens yes, go ahead!

EDIT: please check that somebody has already sent a PR. I think it has completed most of the tasks. only task 4 is remaining. if you want to do it then go ahead. 
sorry :(
